
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://148.70.72.182:3306/exception?serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
#    url: jdbc:mysql://127.0.0.1:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Xyyxyy123
server:
  port: 8080
zjh:
  name: 张嘉豪
# swagger相关配置
#swagger:
#  swaggerable: true #是否开启Swagger，true:开启，false:关闭。关闭时，swaggerUI界面不再显示接口列表
#  title: 开放接口文档  #swagger文档名称
#  description: REST-API在线文档文档 #swagger文档描述
#  termsOfServiceUrl: "http://zjhxyy.cn"
#  version: 2.0 #swagger文档版本
#  apis:
#    base-package: cn.temp.tempbeans.controller #待生成Swagger API文档的controller的包名
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: false
