#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.139.52:8761/eureka/

server:
  port: 8765
spring:
  application:
    name: eureka-client
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.139.52:9900