eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          searchPaths: respo
          uri: https://github.com/forezp/SpringcloudConfig/
          username: zjhChester
          password: Abcd35873

