management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 8881
spring:
  application:
    name: config-client
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
