#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: service-feign
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.139.52:9900
feign.hystrix.enabled: true
